export const ACCOUNT_INITIALIZE = "ACCOUNT_INITIALIZE";
export const ACCOUNT_INPUT_DATA = "ACCOUNT_INPUT_DATA";
export const ACCOUNT_UPDATE_DATA = "ACCOUNT_UPDATE_DATA";
export const ACCOUNT_DELETE_DATA = "ACCOUNT_DELETE_DATA";
export const IS_ADD_DELETE_DATA = "IS_ADD_DELETE_DATA";
export const CURRENT_KEY = "CURRENT_KEY";
