export const CAR_COMPANYLIST_SEARCH = "CAR_COMPANYLIST_SEARCH";
export const CAR_MODELLIST_SEARCH = "CAR_MODELLIST_SEARCH";

export const CAR_INITIALIZE = "CAR_INITIALIZE";
export const CAR_ID_UPDATE = "CAR_ID_UPDATE";
export const CAR_COMPANY_UPDATE = "CAR_COMPANY_UPDATE";
export const CAR_MODEL_UPDATE = "CAR_MODEL_UPDATE";
export const CAR_YEAR_UPDATE = "CAR_YEAR_UPDATE";
