//상수와 관련된 파일
export const PAGE_UPDATE = "PAGE_UPDATE";

export const DEPOSIT_INITIALIZE = "DEPOSIT_INITIALIZE";
export const DEPOSIT_ADD = "DEPOSIT_ADD";
export const DEPOSIT_UPDATE = "DEPOSIT_UPDATE";
export const DEPOSIT_DELETE = "DEPOSIT_DELETE";

export const CAR_COMPANYLIST_SEARCH = "CAR_COMPANYLIST_SEARCH";
export const CAR_MODELLIST_SEARCH = "CAR_MODELLIST_SEARCH";

export const CAR_INITIALIZE = "CAR_INITIALIZE";
export const CAR_ID_UPDATE = "CAR_ID_UPDATE";
export const CAR_COMPANY_UPDATE = "CAR_COMPANY_UPDATE";
export const CAR_MODEL_UPDATE = "CAR_MODEL_UPDATE";
export const CAR_YEAR_UPDATE = "CAR_YEAR_UPDATE";
